import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from '../models/Product.js';
import User from '../models/User.js';
import CarbonReport from '../models/CarbonReport.js';

dotenv.config();

const connectDB = async () => {
  await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/ecochain');
  console.log('MongoDB connected for seeding...');
};

const products = [

  // ─── SMARTPHONES ───────────────────────────────────────────────
  {
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Smartphones',
    price: 134999,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&h=450&fit=crop',
    description: 'Galaxy AI-powered flagship with titanium design, embedded S Pen, and 200MP camera.',
    ecoScore: 68,
    carbonFootprint: 78,
    repairabilityScore: 4.8,
    lifespanYears: 4,
    maintenanceCostYear: 4500,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Titanium', 'Gorilla Glass Armor', 'Recycled Aluminum'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use Samsung Trade-In or drop off at any authorised Samsung service centre.',
    aiSummary: 'Samsung Galaxy S24 Ultra is a powerful AI flagship. The titanium frame and 7-year update support extend its lifespan. The S Pen boosts productivity significantly.',
    aiSustainabilityScore: 67
  },
  {
    name: 'Apple iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'Smartphones',
    price: 159900,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=450&fit=crop',
    description: 'Most advanced iPhone featuring titanium design and A17 Pro chip.',
    ecoScore: 72,
    carbonFootprint: 65,
    repairabilityScore: 5.5,
    lifespanYears: 5,
    maintenanceCostYear: 5500,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Titanium', 'Recycled Aluminum', 'Ceramic Shield'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Recycle for free at any Apple Store via the Apple Trade-In programme.',
    aiSummary: 'The iPhone 15 Pro Max titanium frame is durable and lightweight. Apple\'s recycling programme is excellent. Long-term iOS updates are guaranteed.',
    aiSustainabilityScore: 71
  },
  {
    name: 'OnePlus 12R',
    brand: 'OnePlus',
    category: 'Smartphones',
    price: 39999,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=450&fit=crop',
    description: 'Snapdragon 8 Gen 2, 50MP triple camera, 100W SUPERVOOC fast charging.',
    ecoScore: 74,
    carbonFootprint: 52,
    repairabilityScore: 6.2,
    lifespanYears: 4,
    maintenanceCostYear: 2000,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Gorilla Glass 5', 'Aluminum Frame', 'Recycled Packaging'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Drop off at any OnePlus Service Centre or a local e-waste collection point.',
    aiSummary: 'OnePlus 12R delivers premium performance at an affordable price. The 100W fast charging may have some impact on long-term battery health.',
    aiSustainabilityScore: 72
  },
  {
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    category: 'Smartphones',
    price: 99999,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=450&fit=crop',
    description: '50MP quad-camera with Leica optics, Snapdragon 8 Gen 3.',
    ecoScore: 70,
    carbonFootprint: 71,
    repairabilityScore: 5.0,
    lifespanYears: 4,
    maintenanceCostYear: 3500,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Ceramic Back', 'Titanium Frame', 'Gorilla Glass Victus'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use Mi Service Centre or the Xiaomi Exchange Programme.',
    aiSummary: 'Xiaomi 14 Ultra\'s Leica camera system is outstanding. The ceramic body is highly durable.',
    aiSustainabilityScore: 69
  },
  {
    name: 'Nothing Phone 2',
    brand: 'Nothing',
    category: 'Smartphones',
    price: 44999,
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&h=450&fit=crop',
    description: 'Glyph Interface, Snapdragon 8+ Gen 1, 50MP camera, 45W fast charging.',
    ecoScore: 78,
    carbonFootprint: 48,
    repairabilityScore: 6.5,
    lifespanYears: 4,
    maintenanceCostYear: 2200,
    energyRating: 'A+',
    warrantyMonths: 24,
    materials: ['Recycled Aluminum', 'Recycled Plastics', 'Gorilla Glass 5'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Return via Nothing\'s Take-Back Scheme.',
    aiSummary: 'Nothing Phone 2\'s Glyph Interface is unique. Made with recycled materials, making it genuinely eco-friendly.',
    aiSustainabilityScore: 77
  },
  {
    name: 'Realme GT 5 Pro',
    brand: 'Realme',
    category: 'Smartphones',
    price: 35999,
    image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&h=450&fit=crop',
    description: 'Snapdragon 8 Gen 3, 144Hz AMOLED display, 240W UltraDart fast charging.',
    ecoScore: 65,
    carbonFootprint: 60,
    repairabilityScore: 5.5,
    lifespanYears: 3,
    maintenanceCostYear: 1800,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Aluminum Alloy', 'Gorilla Glass 6', 'Polycarbonate'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Drop off at any Realme Service Centre or an e-waste collection point.',
    aiSummary: 'Realme GT 5 Pro delivers a flagship experience at a mid-range price. The 240W charging is incredibly fast.',
    aiSustainabilityScore: 63
  },
  {
    name: 'Motorola Edge 50 Pro',
    brand: 'Motorola',
    category: 'Smartphones',
    price: 31999,
    image: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=600&h=450&fit=crop',
    description: '50MP Sony LYTIA camera, 125W TurboPower charging, IP68 rating.',
    ecoScore: 71,
    carbonFootprint: 55,
    repairabilityScore: 6.0,
    lifespanYears: 4,
    maintenanceCostYear: 1900,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Vegan Leather Back', 'Aluminum Frame', 'Corning Glass'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the Motorola Recycle Programme or drop off at an authorised centre.',
    aiSummary: 'Motorola Edge 50 Pro features an eco-friendly vegan leather back. It comes with 3 years of OS updates plus 4 years of security patches.',
    aiSustainabilityScore: 70
  },
  {
    name: 'iQOO 12',
    brand: 'iQOO',
    category: 'Smartphones',
    price: 52999,
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&h=450&fit=crop',
    description: 'Snapdragon 8 Gen 3, 144Hz 2K E7 AMOLED display, 120W FlashCharge.',
    ecoScore: 66,
    carbonFootprint: 62,
    repairabilityScore: 5.8,
    lifespanYears: 3,
    maintenanceCostYear: 2800,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['AG Glass', 'Aluminum Frame', 'Gorilla Glass'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Drop off at any iQOO/Vivo Service Centre.',
    aiSummary: 'iQOO 12 is excellent for gaming. The Snapdragon 8 Gen 3 delivers the best-in-class performance.',
    aiSustainabilityScore: 65
  },

  // ─── LAPTOPS ───────────────────────────────────────────────────
  {
    name: 'Apple MacBook Air M2',
    brand: 'Apple',
    category: 'Laptops',
    price: 114900,
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&h=450&fit=crop',
    description: 'M2 chip, 13.6" Liquid Retina display, 18-hour battery life.',
    ecoScore: 80,
    carbonFootprint: 147,
    repairabilityScore: 4.5,
    lifespanYears: 7,
    maintenanceCostYear: 4000,
    energyRating: 'A++',
    warrantyMonths: 12,
    materials: ['100% Recycled Aluminum', 'Rare Earth Metals', 'Glass'],
    sparePartsAvailable: false,
    recyclingInstructions: 'Recycle for free at any Apple Retail Store via the Apple Give Back programme.',
    aiSummary: 'MacBook Air M2 is extremely energy-efficient. Built with 100% recycled aluminium. Receives 7+ years of software support.',
    aiSustainabilityScore: 78
  },
  {
    name: 'Lenovo IdeaPad Slim 5 Gen 9',
    brand: 'Lenovo',
    category: 'Laptops',
    price: 62990,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=450&fit=crop',
    description: 'Intel Core Ultra 7, 16GB RAM, 512GB SSD, 14" 2.8K OLED touch display.',
    ecoScore: 75,
    carbonFootprint: 168,
    repairabilityScore: 7.0,
    lifespanYears: 5,
    maintenanceCostYear: 3500,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Recycled Aluminum', 'Post-Consumer Plastic', 'Glass'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use Lenovo ASSET Recovery or drop off at an authorised service centre.',
    aiSummary: 'IdeaPad Slim 5 features a stunning OLED display. The RAM and SSD are user-upgradeable, extending its useful life.',
    aiSustainabilityScore: 73
  },
  {
    name: 'HP Spectre x360 14',
    brand: 'HP',
    category: 'Laptops',
    price: 189999,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&h=450&fit=crop',
    description: 'Intel Core Ultra 7, 2-in-1 convertible, 2.8K OLED touchscreen, HP Dragonfly.',
    ecoScore: 77,
    carbonFootprint: 182,
    repairabilityScore: 5.5,
    lifespanYears: 6,
    maintenanceCostYear: 5000,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Recycled Aluminum', 'Ocean-Bound Plastics', 'Gorilla Glass'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Recycle for free via the HP Planet Partners Programme.',
    aiSummary: 'HP Spectre x360 uses ocean-bound plastic, making it genuinely eco-conscious. The 2-in-1 design is highly versatile.',
    aiSustainabilityScore: 75
  },
  {
    name: 'Dell XPS 15 9530',
    brand: 'Dell',
    category: 'Laptops',
    price: 174990,
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=450&fit=crop',
    description: 'Intel Core i9, 3.5K OLED touch display, RTX 4070, 32GB RAM.',
    ecoScore: 63,
    carbonFootprint: 210,
    repairabilityScore: 5.5,
    lifespanYears: 5,
    maintenanceCostYear: 6000,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['CNC Machined Aluminum', 'Carbon Fiber', 'Corning Glass'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the Dell Reconnect Programme or an authorised Dell service centre.',
    aiSummary: 'Dell XPS 15 is the best laptop for creators. The OLED display is stunning. Consider upgrading RAM and SSD to extend lifespan.',
    aiSustainabilityScore: 62
  },
  {
    name: 'ASUS VivoBook 15 OLED',
    brand: 'ASUS',
    category: 'Laptops',
    price: 54990,
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&h=450&fit=crop',
    description: 'AMD Ryzen 7 7730U, 15.6" 2.8K OLED display, 16GB RAM, 512GB SSD.',
    ecoScore: 72,
    carbonFootprint: 160,
    repairabilityScore: 6.8,
    lifespanYears: 5,
    maintenanceCostYear: 2800,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Aluminum Alloy', 'Recycled Plastics', 'OLED Panel'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the ASUS Recycling Programme or drop off at a local e-waste centre.',
    aiSummary: 'ASUS VivoBook 15 OLED offers best-in-class display quality. The Ryzen 7 processor is highly energy-efficient.',
    aiSustainabilityScore: 70
  },

  // ─── TABLETS ───────────────────────────────────────────────────
  {
    name: 'Samsung Galaxy Tab S9+',
    brand: 'Samsung',
    category: 'Tablets',
    price: 89999,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=450&fit=crop',
    description: '12.4" Dynamic AMOLED 2X display, Snapdragon 8 Gen 2, S Pen included, IP68 rated.',
    ecoScore: 70,
    carbonFootprint: 85,
    repairabilityScore: 5.2,
    lifespanYears: 5,
    maintenanceCostYear: 4200,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Armor Aluminum', 'Gorilla Glass Victus+', 'Recycled Packaging'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the Samsung Trade-In programme or drop off at an authorised service centre.',
    aiSummary: 'Galaxy Tab S9+ is the best tablet for productivity. Comes with 4 years of OS updates and 5 years of security patches.',
    aiSustainabilityScore: 69
  },
  {
    name: 'Apple iPad Pro M4 11"',
    brand: 'Apple',
    category: 'Tablets',
    price: 99900,
    image: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=600&h=450&fit=crop',
    description: 'M4 chip, Ultra Retina XDR OLED display, Apple Pencil Pro support.',
    ecoScore: 76,
    carbonFootprint: 78,
    repairabilityScore: 4.5,
    lifespanYears: 6,
    maintenanceCostYear: 4500,
    energyRating: 'A++',
    warrantyMonths: 12,
    materials: ['100% Recycled Aluminum', 'Tantalum-Free Components', 'Glass'],
    sparePartsAvailable: false,
    recyclingInstructions: 'Recycle via Apple Give Back Programme or at any Apple Store.',
    aiSummary: 'iPad Pro M4 features a revolutionary OLED display and the powerful M4 chip. Apple\'s recycling programmes are industry-leading.',
    aiSustainabilityScore: 75
  },
  {
    name: 'Xiaomi Pad 6',
    brand: 'Xiaomi',
    category: 'Tablets',
    price: 26999,
    image: 'https://images.unsplash.com/photo-1589739900266-43b2843f4c12?w=600&h=450&fit=crop',
    description: 'Snapdragon 870, 11" 2.8K 144Hz LCD display, 33W HyperCharge, 8840mAh battery.',
    ecoScore: 67,
    carbonFootprint: 72,
    repairabilityScore: 6.0,
    lifespanYears: 4,
    maintenanceCostYear: 1800,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Aluminum Alloy', 'Tempered Glass', 'Recycled Packaging'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Drop off at any Mi Service Centre or use the Xiaomi India Recycle Portal.',
    aiSummary: 'Xiaomi Pad 6 offers a premium experience at an affordable price. The 144Hz display is smooth and responsive.',
    aiSustainabilityScore: 65
  },

  // ─── TELEVISIONS ───────────────────────────────────────────────
  {
    name: 'Sony Bravia XR 55" OLED A80L',
    brand: 'Sony',
    category: 'TVs',
    price: 169990,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&h=450&fit=crop',
    description: 'XR Cognitive Processor, OLED panel, Dolby Vision/Atmos, Google TV.',
    ecoScore: 62,
    carbonFootprint: 310,
    repairabilityScore: 5.5,
    lifespanYears: 10,
    maintenanceCostYear: 5500,
    energyRating: 'B',
    warrantyMonths: 12,
    materials: ['OLED Panel', 'Recycled Plastic Stand', 'Aluminum'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use Sony Green Partner Programme or drop off at the nearest Sony service centre.',
    aiSummary: 'Sony Bravia OLED amortises its carbon footprint over 10 years of use. The XR Processor delivers outstanding picture quality.',
    aiSustainabilityScore: 64
  },
  {
    name: 'LG C3 55" OLED TV',
    brand: 'LG',
    category: 'TVs',
    price: 129990,
    image: 'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=600&h=450&fit=crop',
    description: 'OLED evo panel, a9 AI Processor Gen6, Dolby Vision IQ, webOS 23.',
    ecoScore: 60,
    carbonFootprint: 295,
    repairabilityScore: 5.0,
    lifespanYears: 10,
    maintenanceCostYear: 5000,
    energyRating: 'B',
    warrantyMonths: 12,
    materials: ['OLED Panel', 'Recycled Plastic', 'Aluminum Bezel'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Call LG Recycling Helpline: 1800-315-5454 or visit any LG Service Centre.',
    aiSummary: 'LG C3 OLED is the best choice for both gaming and cinematic experiences. Consumes 30% less energy than comparable QLED models.',
    aiSustainabilityScore: 62
  },
  {
    name: 'Samsung Neo QLED 65" QN90C',
    brand: 'Samsung',
    category: 'TVs',
    price: 159990,
    image: 'https://images.unsplash.com/photo-1461151304267-38231e7d4f7d?w=600&h=450&fit=crop',
    description: 'Mini LED backlight, 4K Neo QLED, Neural Quantum Processor 4K, Dolby Atmos.',
    ecoScore: 58,
    carbonFootprint: 340,
    repairabilityScore: 4.5,
    lifespanYears: 8,
    maintenanceCostYear: 5800,
    energyRating: 'B',
    warrantyMonths: 12,
    materials: ['Mini LED Panel', 'Recycled Metal Stand', 'Tempered Glass'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Track energy usage via the Samsung SmartThings Energy App. Use the Samsung Exchange programme at end of life.',
    aiSummary: 'Samsung Neo QLED\'s Quantum Mini LED backlight is exceptionally bright. The built-in Eco Sensor automatically adjusts brightness to save energy.',
    aiSustainabilityScore: 57
  },
  {
    name: 'MI P1 55" 4K Smart TV',
    brand: 'Xiaomi',
    category: 'TVs',
    price: 37999,
    image: 'https://images.unsplash.com/photo-1571415060716-baff5f717c37?w=600&h=450&fit=crop',
    description: '55" 4K Ultra HD, Dolby Vision/Atmos, 30W speaker system, Android TV.',
    ecoScore: 64,
    carbonFootprint: 280,
    repairabilityScore: 5.8,
    lifespanYears: 7,
    maintenanceCostYear: 3200,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['LED Panel', 'Plastic Frame', 'Aluminum Stand'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Drop off at any Mi Service Centre or use a CPCB-registered e-waste collector.',
    aiSummary: 'MI P1 TV is the best value-for-money television in its segment. Dolby Vision and Atmos deliver a premium audio-visual experience.',
    aiSustainabilityScore: 63
  },

  // ─── WASHING MACHINES ───────────────────────────────────────────
  {
    name: 'IFB Senator Smart Touch SX',
    brand: 'IFB',
    category: 'Washing Machines',
    price: 44990,
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&h=450&fit=crop',
    description: '8Kg Front Load, AI-Powered Smart Sense, Aqua Energie technology, 5 Star BEE rating.',
    ecoScore: 87,
    carbonFootprint: 185,
    repairabilityScore: 7.8,
    lifespanYears: 12,
    maintenanceCostYear: 2200,
    energyRating: 'A+++',
    warrantyMonths: 24,
    materials: ['Stainless Steel Drum', 'Recycled ABS', 'Brushless Motor'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Exchange at any IFB Service Centre. Also eligible for municipal bulk waste collection.',
    aiSummary: 'IFB Senator Smart Touch is one of the most energy-efficient washing machines available. Aqua Energie technology reduces water consumption by 30%.',
    aiSustainabilityScore: 88
  },
  {
    name: 'Samsung EcoBubble 8Kg',
    brand: 'Samsung',
    category: 'Washing Machines',
    price: 36490,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=450&fit=crop',
    description: 'EcoBubble Technology, Wi-Fi Smart Control, 5 Star BEE rating, Digital Inverter Motor.',
    ecoScore: 84,
    carbonFootprint: 195,
    repairabilityScore: 7.2,
    lifespanYears: 11,
    maintenanceCostYear: 2400,
    energyRating: 'A++',
    warrantyMonths: 24,
    materials: ['Stainless Steel', 'Recycled Plastics', 'Inverter Motor'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Monitor energy usage via Samsung SmartThings. Use the Samsung Buyback Programme at end of life.',
    aiSummary: 'EcoBubble Technology delivers deep cleaning even in cold water, significantly reducing energy consumption per wash cycle.',
    aiSustainabilityScore: 83
  },
  {
    name: 'LG FHV1408ZWL 8Kg',
    brand: 'LG',
    category: 'Washing Machines',
    price: 42990,
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&h=450&fit=crop',
    description: 'AI Direct Drive motor, Steam Technology, ThinQ Wi-Fi control, 5 Star BEE rating.',
    ecoScore: 89,
    carbonFootprint: 178,
    repairabilityScore: 8.0,
    lifespanYears: 13,
    maintenanceCostYear: 2100,
    energyRating: 'A+++',
    warrantyMonths: 24,
    materials: ['Stainless Steel Drum', 'Alloy Steel Motor', 'ABS Plastic'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Exchange at any LG Service Centre. Local AMC services are also available.',
    aiSummary: 'LG AI Direct Drive is the quietest and most energy-efficient motor available. Steam Technology produces allergy-free, hygienic laundry.',
    aiSustainabilityScore: 90
  },
  {
    name: 'Whirlpool 6.5Kg Magic Clean',
    brand: 'Whirlpool',
    category: 'Washing Machines',
    price: 16490,
    image: 'https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?w=600&h=450&fit=crop',
    description: '6.5Kg Top Load, ZPF Technology, In-Built Heater, 5 Star BEE rating.',
    ecoScore: 73,
    carbonFootprint: 205,
    repairabilityScore: 8.5,
    lifespanYears: 10,
    maintenanceCostYear: 1800,
    energyRating: 'A+',
    warrantyMonths: 24,
    materials: ['Stainless Steel', 'Polypropylene', 'ABS Plastic'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the Whirlpool Exchange Offer or return via an authorised dealer.',
    aiSummary: 'Whirlpool Magic Clean is the best budget washing machine in its class. ZPF Technology reduces water consumption per cycle.',
    aiSustainabilityScore: 72
  },

  // ─── REFRIGERATORS ─────────────────────────────────────────────
  {
    name: 'Samsung 653L Side By Side RF65A977FSR',
    brand: 'Samsung',
    category: 'Refrigerators',
    price: 139990,
    image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&h=450&fit=crop',
    description: 'French Door design, SpaceMax Technology, Twin Cooling Plus, AI Energy Mode.',
    ecoScore: 79,
    carbonFootprint: 480,
    repairabilityScore: 6.5,
    lifespanYears: 15,
    maintenanceCostYear: 3500,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Stainless Steel', 'ABS Plastic', 'CFC-Free Refrigerant'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the Samsung Exchange Programme. Have CFC-free coolant disposed of separately by a certified technician.',
    aiSummary: 'Samsung French Door Fridge\'s SpaceMax Technology maximises internal storage space. AI Energy Mode reduces electricity consumption automatically.',
    aiSustainabilityScore: 78
  },
  {
    name: 'LG 260L Double Door GL-S292RDSY',
    brand: 'LG',
    category: 'Refrigerators',
    price: 28490,
    image: 'https://images.unsplash.com/photo-1563213126-a4273aed2016?w=600&h=450&fit=crop',
    description: 'Smart Inverter Compressor, Multi Air Flow system, Convertible Fridge mode, 3 Star rating.',
    ecoScore: 82,
    carbonFootprint: 390,
    repairabilityScore: 7.5,
    lifespanYears: 12,
    maintenanceCostYear: 2800,
    energyRating: 'A++',
    warrantyMonths: 12,
    materials: ['Stainless Steel Interior', 'ABS Plastic', 'R600a Refrigerant'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Exchange at any LG Service Centre. Have the R600a refrigerant handled by an authorised AMC provider.',
    aiSummary: 'LG Smart Inverter Compressor comes with a 15-year warranty. The R600a refrigerant is environmentally friendly with low global warming potential.',
    aiSustainabilityScore: 81
  },
  {
    name: 'Haier 190L Single Door HRD-1902BS-R',
    brand: 'Haier',
    category: 'Refrigerators',
    price: 14490,
    image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&h=450&fit=crop',
    description: '5 Star Direct Cool, Convertible Magic, Anti-Bacterial Gasket, 2 year warranty.',
    ecoScore: 76,
    carbonFootprint: 320,
    repairabilityScore: 8.2,
    lifespanYears: 10,
    maintenanceCostYear: 1500,
    energyRating: 'A+++',
    warrantyMonths: 24,
    materials: ['Steel Interior', 'PP Plastic', 'CFC-Free Coolant'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the Haier Exchange Programme or return through a local appliance dealer.',
    aiSummary: 'Haier 5-Star Single Door is the best choice for small homes and studios. Very low electricity consumption.',
    aiSustainabilityScore: 75
  },

  // ─── AIR CONDITIONERS ──────────────────────────────────────────
  {
    name: 'Daikin 1.5 Ton 5 Star Inverter FTKF50TV',
    brand: 'Daikin',
    category: 'Air Conditioners',
    price: 49990,
    image: 'https://images.unsplash.com/photo-1631545806609-3c9b4ff50e5e?w=600&h=450&fit=crop',
    description: 'R-32 Refrigerant, PM 2.5 Filter, Coanda Airflow technology, Econavi sensor.',
    ecoScore: 88,
    carbonFootprint: 520,
    repairabilityScore: 7.0,
    lifespanYears: 15,
    maintenanceCostYear: 2500,
    energyRating: 'A+++',
    warrantyMonths: 12,
    materials: ['Copper Condenser', 'R-32 Refrigerant', 'ABS Plastic'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Exchange at any Daikin Service Centre. Have the R-32 refrigerant handled by a certified technician only.',
    aiSummary: 'Daikin\'s R-32 refrigerant has the lowest GWP in its class. Econavi sensor technology continuously optimises energy usage based on room conditions.',
    aiSustainabilityScore: 87
  },
  {
    name: 'Voltas 1.5 Ton 3 Star Inverter 183V ADJ',
    brand: 'Voltas',
    category: 'Air Conditioners',
    price: 37490,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=450&fit=crop',
    description: 'Intellisense Inverter Technology, 4-in-1 Adjustable Cooling modes, R-32 Refrigerant.',
    ecoScore: 80,
    carbonFootprint: 545,
    repairabilityScore: 7.5,
    lifespanYears: 12,
    maintenanceCostYear: 2200,
    energyRating: 'A++',
    warrantyMonths: 12,
    materials: ['Copper Condenser', 'R-32 Refrigerant', 'HDPE Plastic'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Call Voltas Helpline: 1800-110-999 or visit an Authorised Service Centre.',
    aiSummary: 'Voltas is a trusted Made-in-India brand. The R-32 refrigerant is eco-friendly. The 4-in-1 cooling modes make it very versatile.',
    aiSustainabilityScore: 79
  },
  {
    name: 'Blue Star 1 Ton 5 Star Inverter IC512QATU',
    brand: 'Blue Star',
    category: 'Air Conditioners',
    price: 36990,
    image: 'https://images.unsplash.com/photo-1631545806609-3c9b4ff50e5e?w=600&h=450&fit=crop',
    description: 'Precision Inverter Technology, Auto Restart, Self-Cleaning function, Turbo Cool.',
    ecoScore: 83,
    carbonFootprint: 480,
    repairabilityScore: 7.8,
    lifespanYears: 12,
    maintenanceCostYear: 2000,
    energyRating: 'A+++',
    warrantyMonths: 12,
    materials: ['100% Copper Condenser', 'R-32 Refrigerant', 'HIPS Plastic'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Exchange at any Blue Star Service Centre. Avail up to Rs.5,000 off on exchange.',
    aiSummary: 'Blue Star 5-Star AC pays back its price premium within 5 years through electricity savings. The Self-Cleaning feature significantly reduces maintenance costs.',
    aiSustainabilityScore: 82
  },

  // ─── AUDIO ─────────────────────────────────────────────────────
  {
    name: 'boAt Rockerz 550 Pro',
    brand: 'boAt',
    category: 'Audio',
    price: 2499,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=450&fit=crop',
    description: '70-hour battery life, Active Noise Cancellation, ENx Technology, 40mm drivers.',
    ecoScore: 61,
    carbonFootprint: 18,
    repairabilityScore: 4.5,
    lifespanYears: 3,
    maintenanceCostYear: 500,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Recycled Packaging', 'ABS Plastic', 'Vegan Protein Leather'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Drop off at any boAt Recycle point or local e-waste centre.',
    aiSummary: 'boAt Rockerz 550 Pro is the best budget ANC headphone in India. The 70-hour battery life is exceptional for the price.',
    aiSustainabilityScore: 60
  },
  {
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'Audio',
    price: 28990,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=450&fit=crop',
    description: 'Industry-leading ANC, Auto NC Optimizer, 30-hour battery life, Multipoint Connect.',
    ecoScore: 63,
    carbonFootprint: 14,
    repairabilityScore: 3.5,
    lifespanYears: 5,
    maintenanceCostYear: 1200,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Recycled Plastics (35%)', 'Synthetic Leather', 'Aluminum'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the Sony Green Partner Programme. Ear pads can be replaced independently from a Sony Store.',
    aiSummary: 'Sony WH-1000XM5 has the best ANC in the market. Uses 35% recycled plastic. Ear pads are user-replaceable, extending the product lifespan.',
    aiSustainabilityScore: 64
  },
  {
    name: 'JBL Flip 6',
    brand: 'JBL',
    category: 'Audio',
    price: 9999,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=450&fit=crop',
    description: 'IP67 waterproof and dustproof, 12-hour battery, PartyBoost, Dual Passive Radiators.',
    ecoScore: 58,
    carbonFootprint: 12,
    repairabilityScore: 4.0,
    lifespanYears: 4,
    maintenanceCostYear: 800,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Recycled Fabric', 'Recycled Plastic Housing', 'Li-ion Battery'],
    sparePartsAvailable: false,
    recyclingInstructions: 'Use the JBL Recycle Programme or a CPCB-authorised e-waste collector.',
    aiSummary: 'JBL Flip 6 features a recycled fabric cover, making it eco-friendly. IP67 rating ensures it lasts longer with proper care.',
    aiSustainabilityScore: 58
  },
  {
    name: 'Bose QuietComfort 45',
    brand: 'Bose',
    category: 'Audio',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=450&fit=crop',
    description: 'World-class ANC, 24-hour battery life, Aware Mode, Bose SimpleSync.',
    ecoScore: 65,
    carbonFootprint: 16,
    repairabilityScore: 5.0,
    lifespanYears: 5,
    maintenanceCostYear: 1500,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Recycled Plastic', 'Vegan Leather', 'Aluminum'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Exchange at any Bose Service Centre. Ear cushions can be ordered separately to extend the product lifespan.',
    aiSummary: 'Bose QC45 is renowned for its premium build quality and superb wearing comfort over extended listening sessions.',
    aiSustainabilityScore: 64
  },

  // ─── SMARTWATCHES ────────────────────────────────────────────────
  {
    name: 'Apple Watch Series 9 41mm',
    brand: 'Apple',
    category: 'Smartwatches',
    price: 41900,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&h=450&fit=crop',
    description: 'S9 chip, Double Tap gesture, Carbon Neutral certified, Blood Oxygen sensor, ECG.',
    ecoScore: 80,
    carbonFootprint: 28,
    repairabilityScore: 3.5,
    lifespanYears: 5,
    maintenanceCostYear: 2500,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['100% Recycled Aluminum', 'Carbon-Neutral Bands', 'Sapphire Crystal'],
    sparePartsAvailable: false,
    recyclingInstructions: 'Use Apple Trade-In Programme. Apple Watch Series 9 is a certified carbon-neutral product.',
    aiSummary: 'Apple Watch Series 9 is the first carbon-neutral Apple Watch ever produced. Made with 100% recycled aluminium.',
    aiSustainabilityScore: 82
  },
  {
    name: 'Samsung Galaxy Watch 6 Classic',
    brand: 'Samsung',
    category: 'Smartwatches',
    price: 36999,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=450&fit=crop',
    description: 'Sapphire Crystal glass, Rotating Bezel, BP Monitor, ECG, BioActive Sensor.',
    ecoScore: 72,
    carbonFootprint: 32,
    repairabilityScore: 4.5,
    lifespanYears: 4,
    maintenanceCostYear: 2200,
    energyRating: 'A+',
    warrantyMonths: 12,
    materials: ['Stainless Steel', 'Sapphire Crystal', 'Recycled Packaging'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use Samsung Trade-In. Galaxy Watch ships in recycled packaging.',
    aiSummary: 'Galaxy Watch 6 Classic\'s iconic rotating bezel offers excellent usability. The BioActive Sensor provides comprehensive health monitoring.',
    aiSustainabilityScore: 71
  },

  // ─── CAMERAS & ACCESSORIES ──────────────────────────────────────
  {
    name: 'Sony ZV-E10 Mirrorless Camera',
    brand: 'Sony',
    category: 'Cameras',
    price: 62990,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=450&fit=crop',
    description: '24.2MP APS-C Sensor, 4K Video recording, Real-time Tracking AF, Vlogger Kit.',
    ecoScore: 67,
    carbonFootprint: 95,
    repairabilityScore: 6.5,
    lifespanYears: 7,
    maintenanceCostYear: 3500,
    energyRating: 'A',
    warrantyMonths: 12,
    materials: ['Magnesium Alloy', 'Polycarbonate', 'Glass Elements'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the Sony Green Partner Programme. Battery recycling is mandatory and can be done at any Sony service point.',
    aiSummary: 'Sony ZV-E10 is the best mirrorless camera for vloggers. The APS-C sensor delivers excellent image quality for content creation.',
    aiSustainabilityScore: 66
  },

  // ─── POWER BANKS & ACCESSORIES ──────────────────────────────────
  {
    name: 'Anker PowerCore 26800mAh',
    brand: 'Anker',
    category: 'Accessories',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=450&fit=crop',
    description: '26800mAh capacity, 65W total output, USB-C, Quick Charge 3.0.',
    ecoScore: 70,
    carbonFootprint: 22,
    repairabilityScore: 5.0,
    lifespanYears: 4,
    maintenanceCostYear: 400,
    energyRating: 'A',
    warrantyMonths: 18,
    materials: ['Recycled ABS', 'Li-polymer Battery', 'Recycled Packaging'],
    sparePartsAvailable: false,
    recyclingInstructions: 'Drop off at a CPCB-registered e-waste centre. Dispose of the battery separately.',
    aiSummary: 'Anker 26800mAh can fully charge 3 smartphones. Ships in eco-friendly recycled packaging.',
    aiSustainabilityScore: 68
  },
  {
    name: 'Belkin 65W GaN Charger',
    brand: 'Belkin',
    category: 'Accessories',
    price: 3999,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=450&fit=crop',
    description: 'GaN Technology, 3 Ports (2x USB-C + 1x USB-A), 65W total output, compact design.',
    ecoScore: 75,
    carbonFootprint: 8,
    repairabilityScore: 3.0,
    lifespanYears: 5,
    maintenanceCostYear: 200,
    energyRating: 'A++',
    warrantyMonths: 24,
    materials: ['GaN Semiconductor', 'Recycled Plastics', 'Recycled Packaging'],
    sparePartsAvailable: false,
    recyclingInstructions: 'Use the Belkin Warranty Replacement Programme or dispose at an authorised e-waste centre.',
    aiSummary: 'GaN Technology wastes 40% less energy than traditional silicon chargers. Its compact size also makes it ideal for travel.',
    aiSustainabilityScore: 74
  },

  // ─── MONITORS ───────────────────────────────────────────────────
  {
    name: 'LG UltraWide 34WP65C-B',
    brand: 'LG',
    category: 'Monitors',
    price: 49999,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&h=450&fit=crop',
    description: '34" 21:9 Curved VA panel, 100Hz refresh rate, HDR10, USB-C 65W, FreeSync Premium.',
    ecoScore: 74,
    carbonFootprint: 230,
    repairabilityScore: 6.0,
    lifespanYears: 7,
    maintenanceCostYear: 2500,
    energyRating: 'A+',
    warrantyMonths: 36,
    materials: ['Recycled Plastic (25%)', 'LED Panel', 'Aluminum Stand'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use the LG Electronics Take-Back Programme. Certified for WEEE disposal.',
    aiSummary: 'LG UltraWide is the best monitor for productivity and multitasking. Features a body made with 25% recycled plastic.',
    aiSustainabilityScore: 73
  },
  {
    name: 'Dell S2722DGM 27" Gaming',
    brand: 'Dell',
    category: 'Monitors',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=600&h=450&fit=crop',
    description: '27" QHD 2560x1440, 165Hz refresh rate, 1ms MPRT response, AMD FreeSync Premium, Curved.',
    ecoScore: 68,
    carbonFootprint: 210,
    repairabilityScore: 5.5,
    lifespanYears: 6,
    maintenanceCostYear: 2000,
    energyRating: 'A',
    warrantyMonths: 36,
    materials: ['Recycled Plastic (55%)', 'VA Panel', 'Metal Stand'],
    sparePartsAvailable: true,
    recyclingInstructions: 'Use Dell Reconnect or an authorised e-waste recycler.',
    aiSummary: 'Dell S2722DGM is built with 55% recycled plastic. The 165Hz gaming experience is outstanding for competitive gaming.',
    aiSustainabilityScore: 67
  },
];

const seedData = async () => {
  try {
    await connectDB();
    await Product.deleteMany({});
    await CarbonReport.deleteMany({});

    await Product.insertMany(products);
    console.log(`✅ ${products.length} Indian products seeded successfully!`);

    // Create demo admin user
    const adminExists = await User.findOne({ email: 'admin@ecochain.io' });
    if (!adminExists) {
      await User.create({
        name: 'EcoChain Admin',
        username: 'ecochain_admin',
        email: 'admin@ecochain.io',
        phone: '+91 98765 00001',
        password: 'Admin@123',
        role: 'admin'
      });
      console.log('✅ Admin user created: admin@ecochain.io / Admin@123');
    }

    // Create demo regular user
    const userExists = await User.findOne({ email: 'demo@ecochain.io' });
    if (!userExists) {
      const demoUser = await User.create({
        name: 'Arjun Sharma',
        username: 'arjun_eco',
        email: 'demo@ecochain.io',
        phone: '+91 98765 43210',
        password: 'Demo@123',
        role: 'user'
      });

      // Seed carbon reports for demo user
      const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'];
      const footprints = [145, 132, 118, 110, 108, 95];
      const reports = months.map((month, i) => ({
        user: demoUser._id,
        month,
        year: 2025,
        carbonFootprint: footprints[i],
        wasteGeneratedKg: Math.round(footprints[i] * 0.1),
        moneySaved: Math.round(footprints[i] * 50),
        recommendations: ['Switch to LED bulbs', 'Use public transport', 'Repair before replacing']
      }));
      await CarbonReport.insertMany(reports);
      console.log('✅ Demo user created: demo@ecochain.io / Demo@123 with 6 months of carbon reports');
    }

    console.log('\n🌿 EcoChain India database seeding complete!\n');
    console.log('Categories added:');
    const cats = [...new Set(products.map(p => p.category))];
    cats.forEach(c => {
      const count = products.filter(p => p.category === c).length;
      console.log(`  📦 ${c}: ${count} products`);
    });

    process.exit(0);
  } catch (error) {
    console.error('Error seeding:', error);
    process.exit(1);
  }
};

seedData();
